### ISSUE TITLE
SASS version

### ISSUE THREAD

**Issue by TheCrazyKing** [cyan-2048/solid-telekram#2]
I had to force sass version to "1.77.6" in package.json, otherwise the app did not launch correctly. See [this post](https://github.com/element-plus/element-plus/issues/17487) for details.

**Comment by cyan-2048** [comment]
should be fixed now, didn't think bun would install anything higher than 1.77.6 🤔

**Comment by TheCrazyKing** [comment]
Well actually I used npm

**Comment by cyan-2048** [comment]
I think I need to be more specific that bun should be used hmm
bun handles dependencies differently iirc
